spring.application.name=glitchfame

# ================= SERVER =================
server.port=3000

# ================= DATABASE =================
spring.datasource.url=jdbc:postgresql://localhost:5432/glitchfame
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ================= FLYWAY =================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration/postgres

# ================= JWT =================
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# ================= REDIS =================
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=300000
spring.data.redis.timeout=60000

# ================= FRONTEND =================
app.frontend.urls=http://localhost:5173,https://glitchfame1-gv3k.vercel.app,https://glitchfame1-gv3k-le44jgm9u-puneets-projects-c74e2d17.vercel.app

# ================= CLOUDINARY =================
cloudinary.cloud-name=${Cloudinary_CLOUD_NAME}
cloudinary.api-key=${Cloudinary_API_KEY}
cloudinary.api-secret=${Cloudinary_API_SECRET}

# ================= FILE UPLOAD =================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ================= RESEND =================
resend.api.key=${RESEND_API_KEY}