spring.application.name=glitchfame
# Server port
server.port=3000

# Database connection
spring.datasource.url=jdbc:mysql://localhost:3306/glitchfame?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=samara@124
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=300000
# Optional timeout
spring.data.redis.timeout=60000
app.frontend.url=http://localhost:5173
sendgrid.api.key=${SENDGRID_API_KEY}
sendgrid.from.email=${SENDGRID_SENDER_MAIL}

#cloudinary configuration


cloudinary.cloud-name=${Cloudinary_CLOUD_NAME}
cloudinary.api-key=${Cloudinary_API_KEY}
cloudinary.api-secret=${Cloudinary_API_SECRET}

spring.servlet.multipart.max-file-size=1MB
spring.servlet.multipart.max-request-size=1MB

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=samarasimha444@gmail.com
spring.mail.password=fcalyynexfvdlzsa

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true