spring.application.name=glitchfame

# Server
server.port=3000

# ================= DATABASE (NEON POSTGRESQL) =================
spring.datasource.url=jdbc:postgresql://ep-billowing-lab-akpo64eb-pooler.c-3.us-west-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Pg9DXW2avdBb
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ================= FLYWAY =================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration/postgres

# ================= JWT =================
jwt.secret=test_secret_key
jwt.expiration=86400000

# ================= REDIS =================
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=300000
spring.data.redis.timeout=60000

# ================= FRONTEND =================
app.frontend.url=http://localhost:5173

# ================= SENDGRID =================
sendgrid.api.key=test_sendgrid_key
sendgrid.from.email=test@example.com

# ================= CLOUDINARY =================
cloudinary.cloud-name=test_cloud
cloudinary.api-key=test_key
cloudinary.api-secret=test_secret

# ================= FILE UPLOAD =================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ================= MAIL =================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=test@gmail.com
spring.mail.password=testpassword

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true